### ISSUE TITLE
qwef

### ISSUE THREAD

**Issue by quino0627** [quino0627/issue-pr-template-application#3]
### Self Checklist

- [X] 나는 중복 이슈가 있는지 확인 했습니다.
- [X] 나는 적절한 라벨을 설정 했습니다. epic에 더해 feature, refactoring, performance 등의 라벨을 추가했습니다.
- [X] 나는 이슈의 제목을 단언형으로 작성했습니다. (ex. --- 구현, --- 리팩토링)
- [X] 나는 해당 이슈를 관리하기 위해 마일스톤을 생성했습니다.

### 개요

asdf

### 구현까지의 어프로치, 혹은 설계 방향을 고려하고 있는 게 있다면 작성해주세요

asdf

### 세부 태스크

```[tasklist]
### Tasks
- [ ] #994 
- [ ] #1106 
- [ ] (not critical) Create a headless component library
- [ ] Implement the new bezier-react components
```

### References

qwef

**Comment by quino0627** [comment]
```[tasklist]
- [ ] asdf
```
